-- Migration number: 0003 	 2025-09-07T08:32:19.257Z
CREATE TABLE bonds (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  sold BOOLEAN NOT NULL DEFAULT FALSE,
  email TEXT NOT NULL,
  price INTEGER NOT NULL,
  currency TEXT NOT NULL,
  location TEXT NOT NULL
);
